apiVersion: v1
kind: Service
metadata:
  name: iris-demo-nodeport
  namespace: pipeline
spec:
  type: NodePort
  selector:
    task-name: iris-server-1772168553475
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30080
